import re
print(re.match("f..","food"))
print(re.match("f..","seafood"))
print(re.search("f..","food"))
print(re.search("f..","seafood"))
print(re.search("f..","seafood is food"))
m=re.search("f..","seafood is food")
print(m.group())
m2=re.findall("f..","seafood is food")
print(m2)
for m in re.finditer("f..","seafood is food"):
    print(m.group())
mlist=re.split("-","2018-11-16")
print(mlist)
print(re.sub("f(..)","g\\1","food"))
myre=re.compile("f..")
m=myre.findall("seafood is funny")
print(m)
m=re.split("o","seafood is food")
print(m)